name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pip
      run: sudo  pip install html5validator
    - name: Deploy to foo-bar.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'josedom24@surge.sh'
        project: './_build/'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}    
